-- Initial schema for PG Manager.
-- IDs are UUIDs generated by PostgreSQL (gen_random_uuid() is built in since PostgreSQL 13).
-- Enum-like columns use VARCHAR + CHECK instead of PostgreSQL ENUM types: they map to plain
-- strings in Java and are easy to extend with a new migration.

CREATE TABLE users (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,      -- stored lower-case by the application
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL CHECK (role IN ('ADMIN', 'MANAGER')),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE properties (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name       VARCHAR(150) NOT NULL,
    address    VARCHAR(500) NOT NULL,
    city       VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE rooms (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    property_id UUID        NOT NULL REFERENCES properties (id) ON DELETE CASCADE,
    room_number VARCHAR(20) NOT NULL,
    capacity    INT         NOT NULL CHECK (capacity > 0),
    UNIQUE (property_id, room_number)                -- also serves as the index on property_id
);

CREATE TABLE beds (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    room_id    UUID        NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    bed_number VARCHAR(20) NOT NULL,
    status     VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'OCCUPIED')),
    UNIQUE (room_id, bed_number)
);

CREATE TABLE tenants (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name             VARCHAR(100)   NOT NULL,
    phone            VARCHAR(20)    NOT NULL,
    email            VARCHAR(255),
    joining_date     DATE           NOT NULL,
    monthly_rent     NUMERIC(10, 2) NOT NULL CHECK (monthly_rent >= 0),
    security_deposit NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (security_deposit >= 0),
    status           VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'CHECKED_OUT')),
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE INDEX idx_tenants_status ON tenants (status);

-- Occupancy history: one row per stay. check_out IS NULL means the stay is current.
-- Tenants and beds cannot be deleted while history references them (default NO ACTION),
-- so past occupancy is never lost silently.
CREATE TABLE tenant_bed_history (
    id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID        NOT NULL REFERENCES tenants (id),
    bed_id    UUID        NOT NULL REFERENCES beds (id),
    check_in  TIMESTAMPTZ NOT NULL DEFAULT now(),
    check_out TIMESTAMPTZ,
    CHECK (check_out IS NULL OR check_out >= check_in)
);

CREATE INDEX idx_history_tenant ON tenant_bed_history (tenant_id);
CREATE INDEX idx_history_bed ON tenant_bed_history (bed_id);

-- Database-level safety net against double booking, even if two check-ins race each other:
-- a bed can have at most one open stay, and a tenant can be in at most one bed at a time.
CREATE UNIQUE INDEX uq_history_open_bed ON tenant_bed_history (bed_id) WHERE check_out IS NULL;
CREATE UNIQUE INDEX uq_history_open_tenant ON tenant_bed_history (tenant_id) WHERE check_out IS NULL;

CREATE TABLE payments (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id      UUID           NOT NULL REFERENCES tenants (id),
    amount         NUMERIC(10, 2) NOT NULL CHECK (amount > 0),
    month          CHAR(7)        NOT NULL CHECK (month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),  -- e.g. 2026-10
    payment_date   DATE,
    status         VARCHAR(20)    NOT NULL CHECK (status IN ('PAID', 'PENDING')),
    payment_method VARCHAR(20)    CHECK (payment_method IN ('CASH', 'UPI', 'BANK_TRANSFER')),
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),
    -- A PAID payment must say when and how it was paid; a PENDING one may leave these empty
    CHECK (status = 'PENDING' OR (payment_date IS NOT NULL AND payment_method IS NOT NULL))
);

CREATE INDEX idx_payments_tenant ON payments (tenant_id);
CREATE INDEX idx_payments_status ON payments (status);

CREATE TABLE maintenance_requests (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    property_id UUID         NOT NULL REFERENCES properties (id),
    tenant_id   UUID         REFERENCES tenants (id),   -- optional: some issues are property-wide
    title       VARCHAR(200) NOT NULL,
    description TEXT,
    priority    VARCHAR(10)  NOT NULL DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    status      VARCHAR(20)  NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED')),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_maintenance_property ON maintenance_requests (property_id);
CREATE INDEX idx_maintenance_status ON maintenance_requests (status);
